name: NestJS Tests

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    if: github.event.pull_request.draft == false
    runs-on: local-ubuntu
    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }} 
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        DATABASE_DB: ${{ secrets.DATABASE_DB }}
        GRPC_HOST: ${{ secrets.GRPC_HOST }}
        GRPC_PORT: ${{ secrets.GRPC_PORT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 11

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          rm -rf node_modules
          pnpm store prune
          pnpm install --frozen-lockfile
          pnpm update @juice11-micro/contracts

      # Generate /generated folder with SQL queries
      - name: Generate SQL Types
        run: pnpm run db:types

      # Compile code
      - name: Build application
        run: |
          pnpm build

      - name: Run unit tests
        run: pnpm test

      - name: Run e2e tests
        run: pnpm test:e2e
